name: CI/CD Sentiment Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install transformers datasets evaluate

      # 4. Run sanity tests to ensure dataset and tokenizer load correctly
      - name: Run sanity tests
        run: |
          python - <<'EOF'
          import pandas as pd
          df = pd.read_csv("data/raw/social_sentiment.csv")
          assert not df.empty, "Dataset is empty!"
          from transformers import AutoTokenizer
          tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment-latest")
          print("Dataset and tokenizer loaded successfully.")
          EOF

      # 5. Run model training
      - name: Run model training
        run: |
          python src/train.py
